# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-03 23:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('location_long_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('humidity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.Humidity')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.Location')),
                ('temperature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.Temperature')),
            ],
        ),
        migrations.RemoveField(
            model_name='datacollect',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='datacollect',
            name='temperature',
        ),
        migrations.DeleteModel(
            name='DataCollect',
        ),
    ]
